title: "Mamedul Islam | Freelance Web Developer & E-commerce Expert"

author: 
  name: mamedul
  email: md.mamedulislam@gmail.com
  
description: "Mamedul Islam is a top-rated freelance web developer, designer, and expert in WordPress, WooCommerce, and Shopify. Delivering professional, custom web solutions from home."
keywords: "freelance, web developer, web designer, WordPress expert, WooCommerce expert, Shopify expert, PWA, full-stack, frontend, backend, custom themes, plugin development, remote freelancer"

meta_tags:
  charset: UTF-8
  content_type: text/html
  compatible: IE=edge,chrome=1
  cache_control: public
  viewport: width=device-width, initial-scale=1.0
  author: MAMEDUL ISLAM
  email: md.mamedulislam@gmail.com
  contact: md.mamedulislam@gmail.com
  reply_to: md.mamedulislam@gmail.com
  generator: Designed by MAMEDUL ISLAM
  copyright: Copyright by MAMEDUL ISLAM
  language: English
  robots: INDEX, FOLLOW
  coverage: Worldwide
  distribution: Global
  rating: General
  owner: MAMEDUL ISLAM
  revisit_after: 3 days
  target: all
  classification: Personal
  designer: MAMEDUL ISLAM
  icon: /favicon.ico
  apple_mobile_web_app_capable: yes
  apple_mobile_web_app_status_bar_style: black
  apple_touch_fullscreen: yes
  apple_touch_icon_76x76: /assets/icons/apple-touch-icon/76x76.png
  apple_touch_icon_120x120: /assets/icons/apple-touch-icon/120x120.png
  apple_touch_icon_180x180: /assets/icons/apple-touch-icon/180x180.png
  apple_touch_startup_image: /assets/icons/apple-touch-icon/.png
  sitemap: /sitemap.xml
  opensearch: /opensearch.xml
  msapplication_config: none
  dcterms:
    title: "Mamedul Islam | Freelance Web Developer"
    subject: "Portfolio of a Freelance Web Developer and E-commerce Expert"
    language: "en-US"
  og:
    title: "Mamedul Islam | Freelance Web Developer & E-commerce Expert"
    image: "/assets/images/Mamedul_02.jpg"
    description: "Top-rated freelancer specializing in custom WordPress, WooCommerce, and Shopify development. Delivering professional web solutions and creative designs."
    url: "https://mamedul.github.io"
    type: "website"
    site_name: "Mamedul's Portfolio"
    locale: "en_US"
  twitter:
    card: "summary_large_image"
    description: "Top-rated freelancer specializing in custom WordPress, WooCommerce, and Shopify development. Delivering professional web solutions and creative designs."
    title: "Mamedul Islam | Freelance Web Developer"
    image: "/assets/images/Mamedul_02.jpg"
    creator: "@mamedul"


# set to true to display post-excerpts on the Home Page
show_excerpts: true

# Date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this

mamedul:
  date_format: "%d/%m/%Y"

  # generate social links in footer
  social_links:
    twitter: mamedul
    github:  mamedul
    facebook:  md.mamedul
    twitter:  mamedul
    instagram: mamedul


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

# Outputting
permalink: /blogs/:categories/:title

# Blog pagination
paginate: 5
paginate_path: "/blogs/page/:num/"

# Build settings
markdown: kramdown
exclude: ["README.md"]

plugins:
 - jekyll-feed
 - jekyll-sitemap
 # - jekyll-seo-tag
