title: "Freelancer Mamedul Islam :: Personal website for work and my portfolios &#x7c; Top rated Freelancer &#x7c; Personal website and creativity demo"

author: 
  name: mamedul
  email: mamedul@mamedul.ml
  
description: mamedul.gitgub.io is a personal website of Mamedul Islam. He is a top rated full-time freelancer and working from home. The website is using for works & portfolio

meta_tags:
  charset: UTF-8
  content_type: text/html
  compatible: IE=edge,chrome=1
  cache_control: public
  viewport: width=device-width, initial-scale=1.0
  author: MAMEDUL ISLAM
  email: mamedul@mamedul.ml
  contact: mamedul@mamedul.ml
  reply_to: mamedul@mamedul.ml
  generator: Designed by MAMEDUL ISLAM
  copyright: Copyright by MAMEDUL ISLAM
  language: English
  robots: INDEX, FOLLOW
  coverage: Worldwide
  distribution: Global
  rating: General
  owner: MAMEDUL ISLAM
  revisit_after: 3 days
  target: all
  classification: Personal
  designer: MAMEDUL ISLAM
  icon: /favicon.ico
  apple_mobile_web_app_capable: yes
  apple_mobile_web_app_status_bar_style: black
  apple_touch_fullscreen: yes
  apple_touch_icon_76x76: /assets/icons/apple-touch-icon/76x76.png
  apple_touch_icon_120x120: /assets/icons/apple-touch-icon/120x120.png
  apple_touch_icon_180x180: /assets/icons/apple-touch-icon/180x180.png
  apple_touch_startup_image: /assets/icons/apple-touch-icon/.png
  sitemap: /sitemap.xml
  opensearch: /opensearch.xml
  msapplication_config: none
  dcterms:
    title: "Freelancer Mamedul Islam :: Personal website for work and my portfolios &#x7c; Top rated Freelancer &#x7c; Personal website and creativity demo"
    subject: "Freelancer Mamedul Islam :: Personal website for work and my portfolios &#x7c; Top rated Freelancer &#x7c; Personal website and creativity demo"
    language: en-US
  og:
    title: "Freelancer Mamedul Islam :: Personal website for work and my portfolios &#x7c; Top rated Freelancer &#x7c; Personal website and creativity demo"
    image: 
    description: mamedul.gitgub.io is a personal website of Mamedul Islam. Mamedul Islam is a top rated full-time freelancer and working from home. The website is using for works & portfolio
    url: mamedul.gitgub.io
    type: website
    site_name: "Freelancer Mamedul Islam :: Personal website for work and my portfolios &#x7c; Top rated Freelancer &#x7c; Personal website and creativity demo"
    locale: en-US
  twitter:
    card: summary_large_image
    description: mamedul.gitgub.io is a personal website of Mamedul Islam. Mamedul Islam is a top rated full-time freelancer and working from home. The website is using for works & portfolio
    title: "Freelancer Mamedul Islam :: Personal website for work and my portfolios &#x7c; Top rated Freelancer &#x7c; Personal website and creativity demo"
    image: 
    creator: "@mamedul"


# set to true to display post-excerpts on the Home Page
show_excerpts: true

# Date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this

mamedul:
  date_format: "%d/%m/%Y"

  # generate social links in footer
  social_links:
    twitter: mamedul
    github:  mamedul
    facebook:  md.mamedul
    twitter:  mamedul
    instagram: mamedul


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-sitemap
 # - jekyll-seo-tag